name: Pull Request Checks
on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Java 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'

      - name: Build Java Project
        run: ./mvnw package

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Dependencies
        working-directory: slidev
        run: npm ci

      - name: Build Slides
        working-directory: slidev
        run: npm run build